name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Bundle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        with:
          cmd: build
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: bundle
          path: dist/**
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          ref: gh-pages

      - uses: JesseTG/rm@v1.0.0
        with:
          path: ./pages

      - uses: actions/download-artifact@v3.0.2
        with:
          name: bundle
          path: pages
    
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          add: pages
          push: true

      
