name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup node
        uses: actions/setup-node@v3.6.0

      - name: Run `yarn install`
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run `yarn build`
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Updaload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: bundle
          path: dist/**
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout to github pages branch
        uses: actions/checkout@v3.3.0
        with:
          ref: gh-pages

      - name: Clean up old pages content
        uses: JesseTG/rm@v1.0.0
        with:
          path: ./pages

      - name: Download build artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: bundle
          path: pages

      - name: Commit new pages
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: pages
          push: true
