name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Bundle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        with:
          cmd: build
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: bundle
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          repository: legrak/pages-hosting
      
      - uses: actions/download-artifact@v3.0.2
        with:
          name: bundle
      
      - uses: cpina/github-action-push-to-another-repository@v1.5.1
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: 'legrak'
          destination-repository-name: 'pages-hosting'
          user-email: github_actions_bot@github.com
          target-branch: main



      
